const PRIMARY_CORE_DIR = 'agilai-core';
const LEGACY_CORE_DIR = 'bmad-core';
const DOT_PRIMARY_CORE_DIR = `.${PRIMARY_CORE_DIR}`;
const DOT_LEGACY_CORE_DIR = `.${LEGACY_CORE_DIR}`;

module.exports = {
  PRIMARY_CORE_DIR,
  LEGACY_CORE_DIR,
  DOT_PRIMARY_CORE_DIR,
  DOT_LEGACY_CORE_DIR,
  CORE_DIR_CANDIDATES: [PRIMARY_CORE_DIR, LEGACY_CORE_DIR],
  DOT_CORE_DIR_CANDIDATES: [DOT_PRIMARY_CORE_DIR, DOT_LEGACY_CORE_DIR],
};
